### PR TITLE
Added Fade animation for markdown chunks and words

### PR DESCRIPTION
**Pull request by 21prnv**
Added fade animation for markdown chunks and words!.
Demo: 

https://github.com/user-attachments/assets/61ca5605-9083-4ecc-9b37-f31441e85cf6

### CODE REVIEW

**Comment by manishgautammg3994** [comment]
cool

**Comment by FilledStacks** [comment]
Hey, Thanks for the submission. 

I like the implementation but it solves a different problem. 

What I get back is a single string with additional text at the end, that's why I made the implementation the way I did in the example repo. 

I don't get back a list of strings, that list of strings was there so I could emulate how I get back the text from the socket stream when you tap on the FAB. 

We get back a single string with the new text added behind it. 

Not as a list of strings. 

So if you could animate the new text added when the FAB is tapped in the original example then I can review your implementation again.

**Comment by 21prnv** [comment]
ok will change it and raise the pr

**Comment by 21prnv** [comment]
hey @FilledStacks 
You need an animation that adds a new word to the previous chunk only if it makes sense as a complete sentence.. so after my research, I found out that

**how ChatGPT and other models do actually create complete sentences based on the chunks:** 

_Semantic Understanding: I analyze the meaning of the sentence fragments. If the fragment doesn’t form a complete thought, I infer that it needs more to make sense.

"The text comes back as it" sounds incomplete because the phrase "as it" implies that something else is about to be described or explained.
Contextual Continuity: If chunks of text are given in sequence, I maintain a sense of context. So, if one part looks like the beginning of a sentence, and another looks like the continuation, I can merge them based on that understanding.

Common Patterns: In technical use cases (like when receiving text in chunks over sockets), it's common for sentences to be split between chunks, so I assume that if one chunk ends mid-thought and another chunk follows soon after, they likely belong together._


Maybe I'm wrong, but I think that chatGPT and other AI models use their semantic understanding to write complete sentences.


still I tried to add this animation here is a demo:

https://github.com/user-attachments/assets/d2561b87-bbce-4335-a6a5-544f2435c5ee


Please let me know if Im doing anything wrong will update it and raise new pr .

Thank you,
Prnv

**Comment by FilledStacks** [comment]
Hey, 

I appreciate your effort in what you're trying to solve, but it's not the problem. 

We don't get back a list of strings. 

We get back a single string with new text added at the end. 

I don't know how else to describe it to you. Currently your solution is expecting a list of strings, which is not what we get.

**Comment by 21prnv** [comment]
hey @FilledStacks im working on it

**Comment by 21prnv** [comment]
hey @FilledStacks  dane i think i have created the animation that you want 😁

https://github.com/user-attachments/assets/990d3ff7-bd2c-45eb-b4c9-1d3e6f91354c

**Comment by FilledStacks** [comment]
It looks like the solution. 

Could you please use the original Markdown text updating that I had in the example so I can see if the markdown is rendering as it should.

**Comment by FilledStacks** [comment]
Closing this Bounty claimed [by this PR](https://github.com/FilledStacks/markdown_fade_bounty/pull/6)

Thanks for your submission.

**Pull request closed without merging**
