### PR TITLE
Add markdown to html then html to textspan converter

### PR DESCRIPTION
**Pull request by Silfalion**

### CODE REVIEW

**Comment by FilledStacks** [comment]
We don't get back a list of strings. 

We get back a single string with each new word added onto the end of the original string. 

The list of strings is simply there to so that I could concatenate the string to simulate what we get back from the backend. 

You've solved a different problem. 

Re write the code to use my original implementation and only fade in the newly added text at the end of the string. 

You cannot rely on the list of strings. We only get back a single string. 

Example:

"Hello world"
"Hello world, I am Dane"

That string will be rendered in the markdown rendererd, when the first string come It must fade in. When the second notification comes then only ", I am Dane" should be faded in.

**Comment by Silfalion** [comment]
I'm not sure I understand correctly, the explanation and example seem to contrast with one another. Do you mean that when we get a full string, we break it down, and fade bits of it one at a time to give the illusion that it's rendered incrementally? 

Also, I might not be able to use the original implementation, I did get a solution(the ones I replied to on the tweet) but:

- it doesn't fit the description for the expected solution
- using the markdown builder requires a bit more time

I'll see what I can do, let me know if I understand the premise of the issue correctly.

Edit: I think I understand what you meant, each new string is the previous plus a new string attached to it, is this correct?

Edit 2: so we would get:

- Hello,
- Hello, Dan
- Hello, Dan, didn't see you in a while
- Hello, Dan, didn't see you in a while, how are you today?

Right?

**Comment by FilledStacks** [comment]
Yes, that is correct. 

That's how the original example was setup with the markdown rendering and also how it's explained in the readme and the original bounty email.

**Comment by Silfalion** [comment]
Thank you for confirming, I had overlooked that aspect.

**Comment by FilledStacks** [comment]
Closing this Bounty claimed [by this PR](https://github.com/FilledStacks/markdown_fade_bounty/pull/6)

Thanks for your submission.

**Pull request closed without merging**
