### PR TITLE
MarkDown Fade Text

### PR DESCRIPTION
**Pull request by AshirShaikh99**
A custom Flutter widget that displays a list of markdown text strings with a fade-in animation effect. TheAnimatedFadeText widget allows for easy integration of animated text in markdown format, making it suitable for various applications such as chat interfaces, tutorials, or dynamic content display.

**Usage**
To use the AnimatedFadeText widget, simply instantiate it in your widget tree and provide a list of markdown strings. Optionally, you can customize the duration of the animation.

**Conclusion**
The AnimatedFadeText widget provides a convenient way to display animated markdown content in your Flutter applications. Its customizable nature, makes it adaptable for various use cases, enhancing the user experience with dynamic text transitions.

https://github.com/user-attachments/assets/eb72d100-746e-4c75-9525-b730755213b5

### CODE REVIEW

**Comment by AshirShaikh99** [comment]
@FilledStacks  Here is the documentation of code with some updates:

A custom Flutter widget that displays a list of markdown text strings with a fade-in animation effect. The`AnimatedFadeText` widget allows for easy integration of animated text in markdown format, making it suitable for various applications such as chat interfaces, tutorials, or dynamic content display.

**Usage**
To use the `AnimatedFadeText` widget, simply instantiate it in your widget tree and provide a list of markdown strings. Optionally, you can customize the duration of the animation.


**Conclusion**
The `AnimatedFadeText` widget provides a convenient way to display animated markdown content in your Flutter applications. Its customizable nature, makes it adaptable for various use cases, enhancing the user experience with dynamic text transitions.

New Screen Recording

https://github.com/user-attachments/assets/f0cd5a2b-71d8-42b9-bb0d-94617040d31a

**Comment by FilledStacks** [comment]
Looks great but you're solving a completely different problem that what I described. 

We get back a single string, not a list of strings. 

The list of strings was there so that I could concatenate a single one when you tap the fab. 

We get back for example:

first notification: "Hello world"
second notification: "Hello world, I am Dane"

When the first notification comes I need to only fade in "Hello world", then the second notification comes I need only ", I am Dane" to fade in.

**Comment by AshirShaikh99** [comment]
@FilledStacks Sorry what do you mean by notification if you can clarify it more I can make it as you want just need further clarification. Thanks!

**Comment by AshirShaikh99** [comment]
@FilledStacks Okay let me make some changes then I hope it should be like this as you want

**Comment by AshirShaikh99** [comment]
@FilledStacks Here is the new update let me know about this


https://github.com/user-attachments/assets/aecdfdb5-4295-445d-8a19-5510bc602a3e

**Comment by FilledStacks** [comment]
Hey, 

You don't understand the problem.

We don't get back a list of strings, we get a single string with the new text concatenated at the end of it. 

I don't know how else to explain it to you I've given multiple examples but your solution still expects a list of strings, which is not what we get back. 

We get a single string from the backend.

**Comment by AshirShaikh99** [comment]
> Hey, 
> 
> 
> 
> You don't understand the problem.
> 
> 
> 
> We don't get back a list of strings, we get a single string with the new text concatenated at the end of it. 
> 
> 
> 
> I don't know how else to explain it to you I've given multiple examples but your solution still expects a list of strings, which is not what we get back. 
> 
> 
> 
> We get a single string from the backend. 

@FilledStacks I understood but you have provided us a list of string and you are saying we don't want to get list of strings so this is confusing. Please elaborate it more if possible

**Comment by AshirShaikh99** [comment]
So you need this whole list of string texts in one concatenated line correct? With word by word animation but why you have provided us the list of strings because from api response perspective we will not have a response in list it will stream actually. So please clear the requirements again because this is a confusion which I have mentioned above

**Comment by FilledStacks** [comment]
Closing this Bounty claimed [by this PR](https://github.com/FilledStacks/markdown_fade_bounty/pull/6)

Thanks for your submission.

**Pull request closed without merging**
