### PR TITLE
- adding animation with markdown

### PR DESCRIPTION
**Pull request by JosephhBh**

### CODE REVIEW

**Comment by manishgautammg3994** [comment]
can't we improve it like this 
```dart
import 'package:flutter/material.dart';
import 'package:flutter_markdown_selectionarea/flutter_markdown_selectionarea.dart';

const markdownChunks = [
  '''
### Problem

We’re building an LLM-based tool for one of our FilledStacks clients.
  ''',
  '''
As with ChatGPT, the response from the LLM is streamed back to us.
  ''',
  '''
The text comes back as it
  ''',
  '''
is being completed.
  ''',
  '''
Here’s an example of how
  ''',
  '''
paragraph would be returned:
  ''',
  '''
**The full paragraph**

“I need every new
  ''',
  '''
word being added to the text to animate in
  ''',
  '''
using a fade functionality. This can be seen when using Gemini chat.”
  ''',
  '''
**How it’s returned**

“I need”
  ''',
  '''
“I need every new word”
  ''',
  '''
“I need every new word
  ''',
  '''
being added to”
  ''',
  '''
“I need every new word being
  ''',
  '''
added to the text”
  ''',
  '''
“I need every new word being added to the text to animate in”
  ''',
];

const defaultMessage = 'Tap FAB to add markdown';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Markdown Streaming Demo',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      home: const MyHomePage(title: 'Markdown Streaming'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({super.key, required this.title});

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  late AnimationController _controller;
  late Animation<double> _opacityAnimation;

  List<String> _currentChunks = []; // Store text chunks
  int _markdownIndex = 0;
  bool _isStreaming = false;
  bool _isPaused = true; // Start in paused state

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 500),
    );
    _opacityAnimation = Tween<double>(begin: 0.0, end: 1.0).animate(
      CurvedAnimation(parent: _controller, curve: Curves.easeIn),
    );
  }

  @override
  void dispose() {
    _controller.dispose();
    super.dispose();
  }

  void _addMarkdown() async {
    if (_isStreaming || _markdownIndex >= markdownChunks.length) return;
    _isStreaming = true;

    while (_markdownIndex < markdownChunks.length) {
      if (_isPaused) {
        await Future.delayed(const Duration(milliseconds: 100));
        continue; // Wait until unpaused
      }

      // Get the next chunk
      final newChunk = markdownChunks[_markdownIndex];
      _currentChunks.add(newChunk); // Add chunk to the list

      // Update the UI
      setState(() {});

      // Start the fade-in animation for the new chunk
      _controller.forward(from: 0.0);
      await Future.delayed(
          const Duration(milliseconds: 600)); // Simulate streaming delay

      _markdownIndex++; // Move to the next index
    }

    // When done streaming, set to paused and change the icon
    setState(() {
      _isStreaming = false; // End streaming
      _isPaused = true; // Set to paused state
    });
  }

  void _togglePause() {
    setState(() {
      _isPaused = !_isPaused;
      if (!_isPaused) {
        _addMarkdown(); // Start adding markdown if resumed
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: ConstrainedBox(
          constraints: const BoxConstraints(maxWidth: 700),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Display previous chunks
              FadeTransition(
                // Ignore it or modify it as per your need
                opacity: _isPaused
                    ? _opacityAnimation
                    : const AlwaysStoppedAnimation(
                        1), //this is just for the animation on play and pause so that it looks refreshed  while clicking on play pause FAB midway
                child: MarkdownBody(
                  data: _currentChunks.join(), // Join all previous chunks
                ),
              ),
              // Animate only the new chunk , The Code For which the whole Bounty is Here, NOTE:-  You Need Ignore above  FadeTransition or improve as per your need
              if (_markdownIndex < markdownChunks.length) ...[
                AnimatedBuilder(
                  animation: _controller,
                  builder: (context, child) {
                    return FadeTransition(
                      opacity: _controller,
                      child: MarkdownBody(
                        data: markdownChunks[
                            _markdownIndex], // Display the new chunk
                      ),
                    );
                  },
                ),
              ],
            ],
          ),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _togglePause,
        tooltip: _isPaused ? 'Resume' : 'Pause',
        child: Icon(_isPaused ? Icons.play_arrow : Icons.pause),
      ),
    );
  }
}
```

**Comment by manishgautammg3994** [comment]
Great choice using the `flutter_animate` package! It really enhances the animations in the app!,
Superb

**Comment by FilledStacks** [comment]
Awesome, I'm checking this out now.

**Comment by FilledStacks** [comment]
Hi, thank you for the submission. 

This does not respect the markdown structure. With this implementation the markdown is broken into pieces which means I can't highlight and copy it in the final UI. 

bounty-error

**Pull request closed without merging**
