### PR TITLE
Done with Fade in

### PR DESCRIPTION
**Pull request by Colin-Stark**
This is a sample of the text animation completed with the fade in logic

### CODE REVIEW

**Comment by Colin-Stark** [comment]
I have added a typewriter Effect to mimic the pattern of AI like Gemini and Chatgpt so that is seem as it writing the text in following the completing model of AI

**Comment by FilledStacks** [comment]
Hi,

You're not solving the problem that the original Flutter repo asked you to solve, this is a completely different problem. 

We don't have a list of strings. 

We render a single string in the markdown. One string. 

The string will have new text added to it on the backend and a new string will be returned with the added text. 

We don't get back a list of strings. 

We get:

"## Problem

This is"

Then we get 

"## Problem

This is the main issue with what"

Then we get 

"## Problem

This is the main issue with what we're trying to solve."

They come back as a single string. 

The only reason I had the list in the repo is to emulate how text gets added onto the single string when you tap the FAB. 

If you can implement the fade in functionality using the original Flutter example in this repo then I can review your code again.

**Comment by Colin-Stark** [comment]
so you want the new string to be added at every fab button tap?

**Comment by Colin-Stark** [comment]
I have added a new implementation that adds chunk of data assuming it was being fetched from socket.io

**Comment by FilledStacks** [comment]
Add a screen recording of the text fading in and please use the original text from the list of strings that I added.

**Comment by Colin-Stark** [comment]
https://github.com/user-attachments/assets/22e2a619-05a1-441d-a917-f1ee0abae075

**Comment by FilledStacks** [comment]
Hey,

I don't think you understand the problem that was requested. 

You're using the list of strings, which is not what we get back. 

We get a single string back from the backend. 

I don't know how else to explain that to you.

**Comment by FilledStacks** [comment]
Closing this Bounty claimed [by this PR](https://github.com/FilledStacks/markdown_fade_bounty/pull/6)

Thanks for your submission.

**Pull request closed without merging**
