### PR TITLE
Add animation by maintaining markdown structure

### PR DESCRIPTION
**Pull request by JosephhBh**
https://github.com/user-attachments/assets/8fc5d181-890f-4e52-a813-6fd626ef4d32

### CODE REVIEW

**Comment by FilledStacks** [comment]
You solved a different problem. 

We only get one string back, not a list of strings. 

The list of strings was simply so I can concatenate the single string in order for you to see how we get strings back from our backend. 

We only get back a single string, not a list of string, each string has an additional piece of text at the end. .i.e.

First notification: "Hello world"
Second notification: "Hello world, I am Dane".

When the first notification comes through I need "Hello world" to fade in. 
When the second notification comes through I need ONLY ", I am Dane" to fade in.

**Comment by JosephhBh** [comment]
@FilledStacks  I created a list that contains a list of the response like so :
[
"Hello World",
"Hello World, I am Dane"
]
And i created a functions that mimics the API call each 400ms to receive the new string from the list and this is the output :
|[

https://github.com/user-attachments/assets/7e04f453-3d37-416a-a593-388a1e29809a

](url)

**Comment by JosephhBh** [comment]
@FilledStacks any updates if these are the changes needed ?

**Comment by FilledStacks** [comment]
This implementation will not respect markdown rendering since the widgets are broken into separate pieces

Could you add a code block that spans over 3 responses to see what it does. 

```dart

final markdown = [
'''
```
This is a
''',
'''
Code block that will be rendered
''',
'''
When the markdown completes
```
''',



]




```

**Pull request closed without merging**
