### PR TITLE
Implemented FadeStreamingText widget for animated markdown display

### PR DESCRIPTION
**Pull request by mibrar-dev**
# Gemini-like Effect Implementation in FadeStreamingText Widget

## Video of How It Looks

@FilledStacks 

https://github.com/user-attachments/assets/faaba3df-e6f5-4a53-91a5-4a6aa38a983d

### CODE REVIEW

**Comment by FilledStacks** [comment]
Looks nice, but you've solved a different problem. 

We get back a single string, each string has an additional piece of the text added to it. 

We don't ever get back a list of strings, that list was there, with my original markdown addition function to concatenate a single string which simulates what we get back from the backend. 

We get back "Hello world", then "Hello world, I'm dane". 

When the first one comes back "Hello world" should fade in, when the second one comes back, only "I'm Dane" should fade in.

**Comment by mibrar-dev** [comment]
https://github.com/user-attachments/assets/caf5c27e-016e-430d-8ee3-5b01d1b736e9

There is only 1 string now if you look in the main file it concatenates the new with previous and send it to the stream so it's mimicking what you have mentioned above.

let me know if there's anything else.


I don't think you will see much difference in the new video but I have attached it.
@FilledStacks

**Comment by FilledStacks** [comment]
Could you please slow down the parts being added and add a video so I can see how that looks.

**Comment by mibrar-dev** [comment]
https://github.com/user-attachments/assets/3488d434-06ef-4ae1-b891-b0012c331c36

@FilledStacks Here I have slowed it down

**Comment by FilledStacks** [comment]
Closing this Bounty claimed [by this PR](https://github.com/FilledStacks/markdown_fade_bounty/pull/6)

Thanks for your submission.

**Pull request closed without merging**
