### PR TITLE
Fade effect added to the text by syedbilal07

### PR DESCRIPTION
**Pull request by syedbilal07**
This pull request enhances the Markdown display functionality by adding a fade-in animation effect for each new chunk of text as it’s added to the view, similar to the incremental loading style in Gemini chat. The following updates were made:

Incremental Fade Animation: Just so you know – only newly added text fades in, ensuring previously displayed text remains static, as requested.
Modified _addMarkdown Method: Updated to reset and start the animation each time new text is added, with the fade effect limited to just the new content.
_animationController and AnimatedBuilder: These components work together to control the fade-in timing and selectively apply the effect to new text chunks.

### CODE REVIEW

**Comment by FilledStacks** [comment]
Hey, thanks for your submission. 

This implementation breaks the UI into pieces which causes 2 problems:

1. You cannot highlight and select the UI on Flutter Web
2. There's a jump with the previous text when new text is added as you can see in the video below


https://github.com/user-attachments/assets/905b1485-4d9b-44a6-a857-5d9fe505f240

**Comment by syedbilal07** [comment]
Hi,

I have checked the video. Can I make changes to the code? Do I still have time to change?

Thanks,
Syed
________________________________

**Comment by FilledStacks** [comment]
Sure, you can make as many revisions as you need

**Comment by FilledStacks** [comment]
Closing this Bounty claimed [by this PR](https://github.com/FilledStacks/markdown_fade_bounty/pull/6)

Thanks for your submission.

**Pull request closed without merging**
